# Default values for scheduler-plugins-as-a-second-scheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

scheduler:
  name: custom-scheduler
  image: us-central1-docker.pkg.dev/saas-test-omfe/k8s-docker/scheduler:v1.0.0
  replicaCount: 1
  leaderElect: false

controller:
  name: custom-controller
  image: us-central1-docker.pkg.dev/saas-test-omfe/k8s-docker/controller:v1.0.0
  replicaCount: 1

# LoadVariationRiskBalancing and TargetLoadPacking are not enabled by default
# as they need extra RBAC privileges on metrics.k8s.io.

plugins:
  enabled: ["NodeResourcesAllocatable"]
  # disabled: [""] # only in-tree plugins need to be defined here

pluginConfig:
- name: NodeResourcesAllocatable
  args:
    mode: Least
    resources:
    - name: cpu
      weight: 1000000
    - name: memory
      weight: 1